{% set name = "cashocs" %}
{% set version = "2.2.0" %}
{% set fenics_version = "2019.1.*" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cashocs-{{ version }}.tar.gz
  sha256: e75aea85213daf7dc93aaeff9339d226ba17023f3a13967bdf01d4a141c9eb3f

build:
  noarch: python
  number: 0
  entry_points:
    - cashocs-convert = cashocs._cli:convert
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - numpy
    - meshio >=4.1.0
    - python >=3.8
    - gmsh >=4.8
    - typing_extensions
    - openssh
    - fenics {{ fenics_version }}
    - scotch <7
    - matplotlib-base
    - scipy

test:
  imports:
    - cashocs
    - cashocs._cli
  commands:
    - cashocs-convert --help

about:
  home: https://github.com/sblauth/cashocs
  summary: Computational Adjoint-Based Shape Optimization and Optimal Control Software
  dev_url: https://github.com/sblauth/cashocs
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  description: cashocs is a software for automatically solving PDE constrained shape optimization and optimal control problems.
  doc_url: https://cashocs.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - sblauth
