{% set name = "cashocs" %}
{% set version = "1.5.15" %}
{% set fenics_version = "2019.1.*" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cashocs-{{ version }}.tar.gz
  sha256: 901769fc2425558e3b11c1e816e88c6845caeb4628074953f59256905cfb286b

build:
  noarch: python
  number: 0
  entry_points:
    - cashocs-convert = cashocs._cli:convert
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numpy >=1.21.0
    - meshio >=4.1.0
    - python >=3.7
    - gmsh >=4.8
    - typing_extensions
    - fenics {{ fenics_version }}

test:
  imports:
    - cashocs
    - cashocs._cli
  commands:
    - cashocs-convert --help

about:
  home: https://github.com/sblauth/cashocs
  summary: Computational Adjoint-Based Shape Optimization and Optimal Control Software
  dev_url: https://github.com/sblauth/cashocs
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  description: cashocs is a software for automatically solving PDE constrained shape optimization and optimal control problems.
  doc_url: https://cashocs.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - sblauth
