{% set name = "cashocs" %}
{% set version = "1.3.0" %}
{% set fenics_version = "2019.1.*" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cashocs-{{ version }}.tar.gz
  sha256: f399d98ee36d40d3babefa95b32dc5fcd83df352c6b29e08411dbb3c04e03143

build:
  noarch: python
  number: 0
  entry_points:
    - cashocs-convert = cashocs._cli:convert
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - deprecated >=1.2.10
    - matplotlib-base
    - meshio >=4.1.0
    - pytest >=6.0.0
    - python >=3.6
    - fenics {{ fenics_version }}

test:
  imports:
    - cashocs
    - cashocs._cli
  commands:
    - cashocs-convert --help

about:
  home: https://github.com/sblauth/cashocs
  summary: Computational Adjoint-Based Shape Optimization and Optimal Control Software
  dev_url: https://github.com/sblauth/cashocs
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  description: cashocs is a software for automatically solving PDE constrained shape optimization and optimal control problems.
  doc_url: https://cashocs.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - sblauth
