schema_version: 1

context:
  name: cashocs
  version: "2.11.0"
  fenics_version: 2019.1.*

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/sblauth/cashocs/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 28d3840b9434f03162ebb0db4f4d65572be7d3974f7f7704107b50fceddfbc5a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - cashocs-convert = cashocs._cli._convert:app
      - cashocs-extract-mesh = cashocs._cli._extract_mesh:app

requirements:
  host:
    - pip
    - setuptools >=61
    - python ${{ python_min }}.*
  run:
    - numpy
    - meshio >=4.1.0
    - python >=${{ python_min }}
    - gmsh >=4.8
    - typing_extensions
    - fenics ${{ fenics_version }}
    - matplotlib-base
    - scipy >=1.10.0
    - typer

tests:
  - script:
      - python -c "import cashocs;print(cashocs.__version__)"
      - cashocs-convert --help
      - pytest tests/ -vv
    requirements:
      run:
        - python ${{ python_min }}.*
        - pytest
    files:
      source:
        - tests/

  - script:
      - python -c "import cashocs;print(cashocs.__version__)"
      - cashocs-convert --help
      - pytest tests/ -vv
    requirements:
      run:
        - python
        - pytest
    files:
      source:
        - tests/

about:
  summary: Computational Adjoint-Based Shape Optimization and Optimal Control Software
  license: GPL-3.0-or-later
  license_file: COPYING
  description: cashocs is a software for automatically solving PDE constrained shape optimization and optimal control problems.
  homepage: https://github.com/sblauth/cashocs
  repository: https://github.com/sblauth/cashocs
  documentation: https://cashocs.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - sblauth
